project:
  type: website

website:
  title: "Thadryan J. Sweeney, MS"
  navbar:
    background: primary
    left:
      - about.qmd
      - cv.qmd
      - blog.qmd
    right:
    - icon: github
      text: Github
      href: https://github.com/thadryanjs
    - icon: mastodon
      text: Mastodon
      href: https://fediscience.org/@thadryanjs
    - icon: twitter
      text: Twitter
      href: https://twitter.com/ThadryanJS
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/thadryan-sweeney-10b938a/
format:
  html:
    theme: theme.scss
    css: styles.css



