---
title: "[ What I Work On ]"
page-layout: full
toc: true
about:
  template: jolla
  links:
    - icon: google
      text: Scholar
      href: https://scholar.google.com/citations?user=KLdJrhgAAAAJ
    - icon: github
      text: Github
      href: https://github.com/thadryanjs
    - icon: mastodon
      text: Mastodon
      href: https://fediscience.org/@thadryanjs
    - icon: twitter
      text: Twitter
      href: https://twitter.com/ThadryanJS
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/thadryan-sweeney-10b938a/
---

## Research Focus

I'm interested in statistical methods to reduce disparities and inefficiencies in healthcare. This currently manifests in work on biostatistical and reinforcement learning approaches to understanding and improving health outcomes in opioid use disorder.

I Previously to identify biomarkers for Alzheimer's Dementia, Heart Failure, and COVID-19. The overarching goal was to find reliable markers of disease or to compare existing methods to determine which diagnostic approach was optimal in terms of expense or invasiveness

## Previous Work

Before starting my PhD, my work fell roughly into five (often overlapping) spheres.

### General Research Programming

I worked on <a href="https://microrna-atlas.omics.kitchen/"> apps </a>
that complement <a href="https://www.frontiersin.org/articles/10.3389/fcell.2022.804164/full"> publications </a>
to make their content easier to use and increase engagement.

### Original Software

I worked on creating new software for unmet needs. One example is our <a href="https://covid.omics.kitchen/"> Bayesian COVID Diagnostics app.</a> This serves to complement our <a href="https://bmcinfectdis.biomedcentral.com/articles/10.1186/s12879-021-06257-7"> manuscript </a> on lateral flow assays for SARS-CoV-2 antibodies as well as providing the user with an easy-to-use tool to avoid the pitfalls of black-and-white thinking about diagnostics and counter-intuitive conditional
probability. Another is <a href="https://omics-kitchen.github.io/ContrApption/"> ContrApption</a>, which is a JavaScript-powered R package that allows to user to create an interactive widget for exploring the results of differential expression experiments or any dataset with similar structure.

### Statistics for biomarkers

I worked on statistical analysis for biomarkers of potential use in Alzheimer's Dementia and Neurological symptoms of COVID-19. Publications related to this can be found on my <a href="https://scholar.google.com/citations?user=KLdJrhgAAAAJ&hl=en"> Google Scholar </a> page.

### Statistics and genomics for basic science

For an example of this, check out our <a href="https://onlinelibrary.wiley.com/doi/full/10.1002/advs.202200829"> manuscript </a>
on stress-dependent signatures of cellular and extracellular tRNA-derived small RNAs (tDRs). We're interested in this from a basic science perspective as well as a potential avenue of biomarkers for diseases.

### "Hacktivism"

I had the privilege of contributing to a <a href="https://mapandscorecard.freefrom.org/"> web tool </a> that allows
users to interact with a dataset that ranks the states in the US based on how well they support the financial well-being of survivors of domestic abuse. I did this as a member of <a href="https://ragtag.org/"> RagTag </a> in support of
<a href="https://www.freefrom.org/"> FREEFROM.</a>

<!-- ## Formal academic-style bio:

Thadryan is a former volunteer Firefighter/EMT and Human Services worker turned Data Scientist interested in biostatistics, programming, and interactive data visualization. He studied Human Biology at Greenfield Community College and American International College and worked in custom antibody production before earning his MS in Bioinformatics at Northeastern University. There he served as a Teaching Assistant for the colleges of Science and Computer and Information Science and completed a co-op at bluebird bio in Cambridge where he stayed on as a contractor while finishing his MS. After graduating he came to Mass General to provide statistical and programming support to the Cardiovascular Research Center before moving to ACTRU. He also teaches an online introductory course in the program where he earned his MS. Thadryan will be leaving ACTRU to pursue a PhD. When not at work he enjoys music, RPGs, and cartooning. -->
