---
title: Summary of the Statistical and Journalistic Errors in Heather Mac Donald's
  Systematic Racism Op-ed
author: "Thadryan Sweeney, MS"
subtitle: A list of my findings on HMD's misdeeds
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
bibliography: sources.bib
---

This document summarizes the errors of statistics and journalism in Heather Mac Donald's WSJ op-ed "The Myth of Systemic Police Racism". This only deals with the papers she cited and refers to - the other statistics are not cited and thus I don't know if there are issues with them.

## Facts

### Statistical Scope

- Mac Donald's claim is that "Police Racism" is a "Myth". In defense of this she uses sources about police shootings *specifically* to make claims about police activities *generally*. This is a fundamentally unsound scientific and statistical practice. The Mac Donald's position is well outside the scope of the citations. 

### The Johnson Paper

- The Johnson et al paper [@Johnson15877] concerns the race of the officer involved in police shootings. It makes no comment about race in all policing outside of shootings. They make no claim about the other elements of policing or whether or not police bias exists generally, even going so far as to say "Black civilians fatally shot by police (relative to White civilians) are more likely to be unarmed and less likely to pose an immediate threat to officers". The authors explain in a retraction (more on this later) [@retraction]:

>"Our article estimated the role of officer characteristics in predicting the race of civilians fatally shot by police. A critique pointed out we had erroneously made statements about racial differences in the probability of being shot, and we issued a correction to rectify the statement. Despite this correction, our work has continued to be cited as providing support for the idea that there are no racial biases in fatal shootings, or policing in general. To be clear, our work does not speak to these issues and should not be used to support such statements."

- The Johnson et al paper [@Johnson15877] was called into question by two other groups of researchers who found mathematical errors [@Knox1261] in the paper's methodology and conflicting results [@Schimmack1263]. One paper presents mathematical evidence that paper is "is mathematically incapable of supporting its central claims" [@Knox1261].

- In response to the questioning, the Johnson et al published a correction [@correction].

- These issues were raised months before Mac Donald published the piece.

- Mac Donald claims that Johnson et al state the following: "no significant evidence of antiblack disparity in the likelihood of being fatally shot by police" [@HMD1]. This quote does not appear anywhere in the paper [@Johnson15877]. This quote is from a preprint [@preprint] (before peer review) server, and is from a draft of a letter [@Johnson1264] by Johnson et al in defense of their work. The quote Mac Donald uses does not appear in the final version, only the draft. The draft was published in August of 2019, the peer reviewed version was published in January of 2020. Mac Donald cited the draft in June of 2020 (note: when I pointed out the quote wasn't in the paper on social media, it was tracked down by twitter user `@ulymelendez`).

> Updates on Johnson et al (since publication of Mac Donald's first op-ed)

- Heather Mac Donald has recently published another op-ed [@HMD2]. In it she states the previous op-ed "quoted the PNAS article’s conclusion verbatim". This is not true because the quote is not in the paper [@Johnson15877].

- Recently the authors called for a issued a request for retraction of their paper [@request], citing Mac Donald by name as misusing their work and stating that their careless wording allowed this to happen. The formal retraction doesn't mention Mac Donald. In addressing the mathematical errors, they state "While our data and statistical approach were appropriate for investigating whether officer characteristics are related to the race of civilians fatally shot by police, they are inadequate to address racial disparities in the probability of being shot" [@retraction]. One of the authors who found the math error in Johnson et al has recently published an article explaining the situation [@medium].

### The Work of Roland Freyer

 - Mac Donald refers to work by "Research by Harvard economist Roland G. Fryer Jr." though does not provide a citation.

 - Searching for research on police by a Harvard Economist of that name reveals a paper [@fryer] that found no evidence of disparities in police shootings but found them in nearly all categories of the police use of force. Heather Mac Donald ignores all other uses of force in her work. The disparities are addressed in the second sentence of his abstract.


## Misc 

Mac Donald cites a study on a the Philadelphia Police Department that found no disparities in shootings [@phili]. Again, only shootings, not all policing. This would make sense as supporting evidence, complementing strong literature support to the authors claim. This is not the case in the case of Heather Mac Donald. It only applies to one city, and one aspect of policing.

## My Takeaway on the facts

The Systemic Racism Op-ed is built around a paper that, at the time of her publication, had been credibly called into question and had contradicting results found. The entire thing hinges around research about shootings even though she is making claims about policing in general, which is fundamentally wrong. She also takes a quote that doesn't exist in the paper. That quote is from a passage of a preprint that did not make it to the peer reviewed version of the letter. Given that the final version that doesn't contain the quote was published months before her paper, this is either negligence or a deliberate effort to pass off non-reviewed work as scientific. She refers to Freyer's work, but conveniently ignores the fact that the majority of his findings did show bias, essentially cherry-picking a study that goes against her conclusions when not taken out of context.

Later the study authors, at least initially, call her out by name as misusing her work and retracted the paper.

## Future work and commentary

I plan on submitting a letter to the editor of the WSJ about the quote being cited as a conclusion to a peer reviewed paper in which is does not appear, and I am working on more posts, both commentary and strictly factual, on her misdeeds.

Most importantly though, I'm looking for collaborator who are interested in presenting her errors widely and publicly. She speaks with a great deal of credibility and confidence, misusing research and statistics in a subtle enough way the average reader thinks they're getting data driven journalism when they're actually getting a pseduo-scientific policy agenda. She is trained as a lawyer, and she argues like one. Unfortunately, she also uses statistics like one - half informed and twisted to support an existing conclusion. I think the left needs to point this out.

I personally believe she is trying to get people, particularly well-off white people, who were starting to listen to the Black community for the first time, to put down their Ipads and go back to their cornflakes. I think her eagerness to do has made her sloppy - [I'm not sure if she even knows that the quote she says is the conclusion of that paper isn't in it](https://twitter.com/ThadryanJS/status/1282034535186739201?s=20).

## Sources