---
author: "Thadryan"
title: "Python for Perl users"
date: "2017-12-21"
description: "All the kids are using Python now."
categories:
  - python
  - perl
---

Recently, I created a quick summary of Python for Perl users for a class, so I thought I would share it here. Perl is a bit of a throwback, so for the uninitiated, it's is a high level level language developed to parse text in unix-like systems.  Quirky and known for being quick to write, if awkward to read, its regular expression and text parsing capability set the standard for languages that followed. It grew in popularity and was implemented for general purpose computing and web use, becoming known as "the duct tape that holds the Internet together". Though its uses has decreased sharply in the era of Python, JavaScript, and Ruby, it played an instrumental role in the Human Genome Project, so it still enjoys use in Bioinformatics.

[This repository](https://github.com/sweeney-th/PerlToPyCrashCourse) has a Jupyter notebook of Python code and explanations, and a file of Perl scripts for contrasting some of the strategies. Enjoy!